var modules =
[
    [ "Basic Library Datatypes Group", "group__basicdatatypes.html", "group__basicdatatypes" ],
    [ "Enumerators with various purposes", "group__enums.html", "group__enums" ],
    [ "Defined and Opaque Structs", "group__allstructs.html", "group__allstructs" ],
    [ "Default stack frame macros", "group__framedefines.html", "group__framedefines" ],
    [ "DW_DLA alloc/dealloc typename&number", "group__dwdla.html", "group__dwdla" ],
    [ "DW_DLE Dwarf_Error numbers", "group__dwdle.html", "group__dwdle" ],
    [ "Libdwarf Initialization Functions", "group__initfunctions.html", "group__initfunctions" ],
    [ "Compilation Unit (CU) Access", "group__compilationunit.html", "group__compilationunit" ],
    [ "Debugging Information Entry (DIE) content", "group__dieentry.html", "group__dieentry" ],
    [ "DIE Attribute and Attribute-Form Details", "group__attrform.html", "group__attrform" ],
    [ "Line Table For a CU", "group__linetable.html", "group__linetable" ],
    [ "Ranges: code addresses in DWARF3-4", "group__ranges.html", "group__ranges" ],
    [ "Rnglists: code addresses in DWARF5", "group__rnglists.html", "group__rnglists" ],
    [ "Locations of data: DWARF2-DWARF5", "group__locations.html", "group__locations" ],
    [ ".debug_addr access:  DWARF5", "group__debugaddr.html", "group__debugaddr" ],
    [ "Macro Access: DWARF5", "group__macro.html", "group__macro" ],
    [ "Macro Access: DWARF2-4", "group__macinfo.html", "group__macinfo" ],
    [ "Stack Frame Access", "group__frame.html", "group__frame" ],
    [ "Abbreviations Section Details", "group__abbrev.html", "group__abbrev" ],
    [ "String Section .debug_str Details", "group__string.html", "group__string" ],
    [ "Str_Offsets section details", "group__str__offsets.html", "group__str__offsets" ],
    [ "Dwarf_Error Functions", "group__dwarferror.html", "group__dwarferror" ],
    [ "Generic dwarf_dealloc Function", "group__dwarfdealloc.html", "group__dwarfdealloc" ],
    [ "Access to Section .debug_sup", "group__debugsup.html", "group__debugsup" ],
    [ "Fast Access to .debug_names DWARF5", "group__debugnames.html", "group__debugnames" ],
    [ "Fast Access to a CU given a code address", "group__aranges.html", "group__aranges" ],
    [ "Fast Access to .debug_pubnames and more.", "group__pubnames.html", "group__pubnames" ],
    [ "Fast Access to GNU .debug_gnu_pubnames", "group__gnupubnames.html", "group__gnupubnames" ],
    [ "Fast Access to Gdb Index", "group__gdbindex.html", "group__gdbindex" ],
    [ "Fast Access to Split Dwarf (Debug Fission)", "group__splitdwarf.html", "group__splitdwarf" ],
    [ "Access GNU .gnu_debuglink, build-id.", "group__gnudebuglink.html", "group__gnudebuglink" ],
    [ "Harmless Error recording", "group__harmless.html", "group__harmless" ],
    [ "Names DW_TAG_member etc as strings", "group__Naming.html", "group__Naming" ],
    [ "Object Sections Data", "group__objectsections.html", "group__objectsections" ],
    [ "Section Groups Objectfile Data", "group__secgroups.html", "group__secgroups" ],
    [ "LEB Encode and Decode", "group__leb.html", "group__leb" ],
    [ "Miscellaneous Functions", "group__miscellaneous.html", "group__miscellaneous" ],
    [ "Determine Object Type of a File", "group__objectdetector.html", "group__objectdetector" ]
];