name: Windows MinGW64 GCC Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: []

jobs:
  test-windows-gcc:
    strategy:
      matrix:
        dep: ["source"]
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          mingw-w64-ucrt-x86_64-gcc
          mingw-w64-ucrt-x86_64-cmake
          mingw-w64-ucrt-x86_64-meson
          mingw-w64-ucrt-x86_64-ninja
          make
        msystem: UCRT64
    # - name: Install dependencies
    #   if: matrix.dep == 'pacman'
    #   run: pacman -S --noconfirm mingw-w64-ucrt-x86_64-

    - name: Setup Meson
      env:
        CC: gcc
        CXX: g++
      run: >
        meson setup build
        --buildtype=debug
    - name: Compile
      run: meson compile -C build
    - name: Test
      run: meson test -C build --suite y3c-stl --print-errorlog

    - name: Check Exported Symbol
      shell: pwsh -command ". '{0}'"
      run: |
        ${VS_INST_PATH} = & "${env:ProgramFiles(x86)}/Microsoft Visual Studio/Installer/vswhere.exe" -latest -property installationPath
        Write-Output "  <-> VS Install Path: ${VS_INST_PATH}"
        Import-Module ${VS_INST_PATH}/Common7/Tools/Microsoft.VisualStudio.DevShell.dll
        Enter-VsDevShell -VsInstallPath ${VS_INST_PATH} -SkipAutomaticLocation -DevCmdArguments '-arch=${{matrix.config.arch}} -no_logo'
        C:\msys64\usr\bin\bash.exe -c "export PATH=\"/usr/bin:$PATH\" &&      dumpbin //exports build/*y3c*.dll | grep -A 10000 RVA | grep -B 10000 Summary | grep -v y3c"

    - name: install
      run: meson install -C build
